name: Hey First Action

on:
  push:
    branches: 
      - master
  pull_request:
    types: [closed]
env:
  name: TomA
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      name: vic3pwa
    steps:
    - name: Run a one-line script
      run: echo Hello, $name!

        
  pull_req_only:

    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [build]
    steps:
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
