name: Naming multi variables

on:
  push:
    branches: 
      - master
  pull_request:
    types: [closed]

env:
  name: TomA

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      name: vic3pwa A.
    steps:
    - name: Run a one-line script
      run: echo Hello, $name!

        
  pull_req_only:

    runs-on: ubuntu-latest
    env:
      pos: graduate at ceni80
    if: github.event_name == 'pull_request'
    needs: [build]
    steps:
    - name: Run a multi-line script
      run: |
        echo Hello $name
        echo I see you are a $pos, you're doing well
