name: Naming multi variables

on:
  push:
    branches: 
      - master
  pull_request:
    types: [closed]

env:
  name: TomA

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      name: vic3pwa A.
    steps:
    - name: Run a one-line script
      run: 
        echo Hello, $name!
        echo Actor: ${{ github.actor }}
        echo Committed By:: ${{ github.event.commits[0].author.name }}

  dump:
    runs-on: [ubuntu-latest]
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
        
  pull_req_only:

    runs-on: ubuntu-latest
    env:
      posi: graduate at ceni80
    if: github.event_name == 'pull_request'
    needs: [build]
    steps:
    - name: Run a multi-line script
      run: |
        echo Hello $name
        echo I see you are a $posi
